"""meditatorMCP Server: expose a chatAgent tool backed by a non-reasoning model.

The tool lets a reasoning model outsource part of its chain-of-thought to a
cheaper, faster non-reasoning model.  Three reasoning modes map to different
sampling strategies:

- verify:     low temperature / low top_p  -> deterministic validation
- explore:    medium temperature / medium top_p  -> continue reasoning
- brainstorm: high temperature / high top_p  -> divergent idea generation
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Literal

from mcp.server.fastmcp import FastMCP
from openai import OpenAI

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

CONFIG_PATH = Path(__file__).parents[2] / ".test_resources" / "config.json"

if CONFIG_PATH.exists():
    _raw_cfg = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
else:
    _raw_cfg = {
        "base_url": os.getenv("MEDITATOR_BASE_URL", "https://api.siliconflow.cn/v1"),
        "model": os.getenv("MEDITATOR_MODEL", "deepseek-ai/DeepSeek-V4-Flash"),
        "api_key": os.getenv("MEDITATOR_API_KEY", ""),
    }

BASE_URL = _raw_cfg.get("base_url", os.getenv("MEDITATOR_BASE_URL"))
MODEL = _raw_cfg.get("model", os.getenv("MEDITATOR_MODEL"))
API_KEY = _raw_cfg.get("api_key", os.getenv("MEDITATOR_API_KEY"))

# ---------------------------------------------------------------------------
# Sampling mode mapping (replaces top_k with temperature + top_p)
# ---------------------------------------------------------------------------

MODE_CONFIG: dict[str, dict[str, float]] = {
    "verify": {"temperature": 0.15, "top_p": 0.20},
    "explore": {"temperature": 0.70, "top_p": 0.85},
    "brainstorm": {"temperature": 1.20, "top_p": 0.95},
}

# ---------------------------------------------------------------------------
# FastMCP server
# ---------------------------------------------------------------------------

mcp = FastMCP("chatAgent")

_client: OpenAI | None = None


def _get_client() -> OpenAI:
    global _client
    if _client is None:
        if not API_KEY:
            raise RuntimeError("API key is not configured.")
        _client = OpenAI(base_url=BASE_URL, api_key=API_KEY)
    return _client


@mcp.tool()
async def chat_agent(
    input_text: str,
    reasoning_mode: Literal["verify", "explore", "brainstorm"] = "explore",
    max_tokens: int = 2048,
    stop: list[str] | None = None,
) -> str:
    """Call a non-reasoning language model to assist reasoning.

    This tool is intended to be invoked by a thinking/reasoning model when it
    needs external help: fact checking, continuing a thought chain that is
    approaching its token budget, or generating diverse candidate ideas.

    Args:
        input_text: The prompt or reasoning fragment to hand to the non-reasoning
            model. Should include enough context for the model to produce useful
            output.
        reasoning_mode: Sampling strategy to use.
            - "verify": low temperature + low top_p, for deterministic validation.
            - "explore": medium temperature + medium top_p, for continuing reasoning.
            - "brainstorm": high temperature + high top_p, for divergent ideation.
        max_tokens: Maximum number of tokens the tool may generate. Use this to
            control context growth instead of truncating manually.
        stop: Optional list of stop sequences. Generation stops when any sequence
            is encountered.

    Returns:
        The text generated by the non-reasoning model.
    """
    cfg = MODE_CONFIG[reasoning_mode]
    client = _get_client()

    messages = [
        {
            "role": "system",
            "content": (
                "You are a concise reasoning assistant. "
                "Continue or refine the user's reasoning fragment. "
                "Do not add meta commentary; respond only with useful reasoning text."
            ),
        },
        {"role": "user", "content": input_text},
    ]

    response = client.chat.completions.create(
        model=MODEL,
        messages=messages,
        temperature=cfg["temperature"],
        top_p=cfg["top_p"],
        max_tokens=max_tokens,
        stop=stop,
        # V4-Flash defaults to thinking=enabled; force non-thinking mode so that
        # temperature/top_p take effect and we get a fast, direct answer.
        extra_body={"thinking": {"type": "disabled"}},
    )

    return response.choices[0].message.content or ""


if __name__ == "__main__":
    mcp.run(transport="stdio")
